name: enet-script-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.5
  - pip:
      - git+https://github.com/nicologhielmetti/hls4ml.git@enet#egg=hls4ml[profiling]
      - ipykernel==6.22.0
      - ipython==8.12.0
      - keras==2.7.0
      - keras-core==0.1.7
      - keras-preprocessing==1.1.2
      - keras-tuner==1.4.5
      - kt-legacy==1.0.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - numpy==1.26.1
      - qkeras==0.9.0
      - seaborn==0.13.1
      - tensorflow==2.7.1
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.7.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.14.0
      - tensorflow-model-optimization==0.7.3
