name: enet-script-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.5
  - pip=23.3.2
  - pip:
      - git+https://github.com/nicologhielmetti/hls4ml.git@enet#egg=hls4ml[profiling]
      - torch==2.1.2
      - keras==2.7.0
      - numpy==1.26.1
      - qkeras==0.9.0
      - seaborn==0.13.1
      - tensorflow==2.7.1
      - tensorflow-datasets==4.9.3
      - opencv-python==4.9.0.80
